FORMAT: 1A
HOST: http://localhost:4090/api/

# phoenix

phoenix api

## 注册 [/auth/register]

### /auth/register [POST]

+ Request (application/json)

        {
            "account": "",
            "password": "",
            "name": "",
            "avatar": ""
        }

+ Response 200 (application/json)

        {
            "result": {
                "user": {
                    "account": "",
                    "name": "",
                    "avatar": ""
                },
                "token": ""
            }
        }

## 登录 [/auth/login]

### /auth/login [POST]

+ Request (application/json)

        {
            "account": "",
            "password": ""
        }

+ Response 200 (application/json)

        {
            "result": {
                "user": {
                    "account": "",
                    "name": "",
                    "avatar": ""
                },
                "token": ""
            }
        }
        
## 获取头像上传token [/auth/getAvatarUploadInfo]

### /auth/getAvatarUploadInfo [GET]

+ Request (application/json)

        {
            "key": ""
        }

+ Response 200 (application/json)

        {
            "result": {
                "account": "",
                "name": "",
                "avatar": "",
                "following": false,
                "followings": [],
                "followers": []
            }
        }
        
## 修改头像 [/auth/changeAvatar]

### /auth/changeAvatar [POST]

+ Request (application/json)

        {
        }

+ Response 200 (application/json)

        {
            "result": {
                "token": "",
                "key": ""
            }
        }
        
        
## 关注 [/follow/follow]

### /follow/follow [POST]

+ Request (application/json)

        {
            "account": ""
        }
        
+ Response 200 (application/json)

        {
            "success": true
        }
     
     

## 取消关注 [/follow/unfollow]

### /follow/unfollow [POST]

+ Request (application/json)

        {
            "account": ""
        }
        
+ Response 200 (application/json)

        {
            "success": true
        }
        
## 获取关注列表 [/follow/getFollowing]

### /follow/getFollowing [GET]

+ Request (application/json)

        {
            "account": ""
        }
        
+ Response 200 (application/json)

        {
          "result": [
            {
                "account": "",
                "name": "",
                "following": true,
                "followings": [],
                "followers": []
            }
          ]
        }
    
    
## 获取粉丝列表 [/follow/getFollower]

### /follow/getFollower [GET]

+ Request (application/json)

        {
            "account": ""
        }
        
+ Response 200 (application/json)

        {
          "result": [
            {
                "account": "",
                "name": "",
                "following": true,
                "followings": [],
                "followers": []
            }
          ]
        }